In [7]:
import pandas as pd
import numpy as np 
from sklearn import preprocessing

MUSHROOMS=pd.read_csv('mushrooms.csv') 

le=preprocessing.LabelEncoder()
mushrooms=MUSHROOMS.apply(le.fit_transform)

target=mushrooms['class']
data=mushrooms.drop('class',axis=1)
data.head()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,5,2,4,1,6,1,0,1,4,0,...,2,7,7,0,2,1,4,2,3,5
1,5,2,9,1,0,1,0,0,4,0,...,2,7,7,0,2,1,4,3,2,1
2,0,2,8,1,3,1,0,0,5,0,...,2,7,7,0,2,1,4,3,2,3
3,5,3,8,1,6,1,0,1,5,0,...,2,7,7,0,2,1,4,2,3,5
4,5,2,3,0,5,1,1,0,4,1,...,2,7,7,0,2,1,0,3,0,1

In [2]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.4)

In [3]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)

1.0

In [4]:
y_pred=dtc.predict(x_test)
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
score

1.0

In [5]:
Y_test=np.array(y_test)
df_dtc=pd.DataFrame(Y_test,columns=['ACTUAL'])
df_dtc['PREDICTED']=y_pred
df_dtc.head(20)

    ACTUAL  PREDICTED
0        1          1
1        1          1
2        1          1
3        0          0
4        1          1
5        0          0
6        1          1
7        1          1
8        1          1
9        1          1
10       0          0
11       0          0
12       1          1
13       0          0
14       1          1
15       0          0
16       1          1
17       0          0
18       0          0
19       1          1