In [1]:
import pandas as pd
import numpy as np 
from sklearn import preprocessing

MUSHROOMS=pd.read_csv('mushrooms.csv') 

le=preprocessing.LabelEncoder()
mushrooms=MUSHROOMS.apply(le.fit_transform)

target=mushrooms['class']
data=mushrooms.drop('class',axis=1)
data.head()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,5,2,4,1,6,1,0,1,4,0,...,2,7,7,0,2,1,4,2,3,5
1,5,2,9,1,0,1,0,0,4,0,...,2,7,7,0,2,1,4,3,2,1
2,0,2,8,1,3,1,0,0,5,0,...,2,7,7,0,2,1,4,3,2,3
3,5,3,8,1,6,1,0,1,5,0,...,2,7,7,0,2,1,4,2,3,5
4,5,2,3,0,5,1,1,0,4,1,...,2,7,7,0,2,1,0,3,0,1

In [10]:
le.fit(MUSHROOMS['cap-shape'])
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
le_name_mapping

{'b': 0, 'c': 1, 'f': 2, 'k': 3, 's': 4, 'x': 5}

In [3]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.5)

In [4]:
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

knn=KNeighborsClassifier(6)
knn.fit(x_train,y_train)
knn.score(x_train,y_train)

0.9985228951255539

In [5]:
y_pred=knn.predict(x_test)

from sklearn.metrics import accuracy_score

score_pred_knn=accuracy_score(y_test,y_pred)
print(score_pred_knn)

0.9972919743968488

In [6]:
Y_test=np.array(y_test)
df_knn=pd.DataFrame(Y_test,columns=['ACTUAL'])
df_knn['PREDICTED']=y_pred
df_knn.head(20)

    ACTUAL  PREDICTED
0        1          1
1        1          1
2        1          1
3        0          0
4        0          0
5        0          0
6        0          0
7        1          1
8        0          0
9        0          0
10       0          0
11       1          1
12       0          0
13       1          1
14       0          0
15       1          1
16       1          1
17       1          1
18       1          1
19       1          1

In [7]:
from sklearn import naive_bayes

gnb=naive_bayes.GaussianNB()
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)

0.9276218611521418

In [8]:
y_pred_gnb=gnb.predict(x_test)
score_pred_gnb=accuracy_score(y_test,y_pred_gnb)
print(score_pred_gnb)

0.9249138355489906

In [9]:
Y_test_gnb=np.array(y_test)
df_gnb=pd.DataFrame(Y_test_gnb,columns=['ACTUAL'])
df_gnb['PREDICTED']=y_pred_gnb
df_gnb.head(20)

    ACTUAL  PREDICTED
0        1          1
1        1          1
2        1          1
3        0          0
4        0          0
5        0          0
6        0          0
7        1          1
8        0          0
9        0          0
10       0          0
11       1          0
12       0          1
13       1          1
14       0          0
15       1          1
16       1          1
17       1          1
18       1          1
19       1          1